backend:
  name: git-gateway
  branch: main

media_folder: "assets/gallery"
public_folder: "/assets/gallery"

site_url: "https://yourultsuperfan.netlify.app"
display_url: "https://yourultsuperfan.netlify.app"

collections:
  - name: "gallery"
    label: "📷 Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - label: "Photo"
        name: "image"
        widget: "image"

      - label: "Caption"
        name: "caption"
        widget: "string"

  - name: "videos"
    label: "🎥 Videos"
    folder: "content/videos"
    create: true

    fields:
      - label: "Video"
        name: "video"
        widget: "file"

      - label: "Title"
        name: "title"
        widget: "string"

  - name: "archives"
    label: "💗 Lizzy Archives"
    folder: "content/archives"
    create: true

    fields:
      - label: "Memory"
        name: "memory"
        widget: "text"

  - name: "letter"
    label: "❤️ Read Me"

    files:
      - label: "Read Me"
        name: "readme"
        file: "content/settings/readme.md"

        fields:
          - label: "Message"
            name: "body"
            widget: "markdown"